# Site settings
title: "Towards Robust and Trustworthy Large Language Models"
email: "llms-robustness-2025@googlegroups.com"
baseurl: ""
url: "llms-robustness-2025.github.io"

navbar-links:
    Overview: "/#overview"
    Speakers: "/#speakers"
    Outline: "/#outline"
    Slides: "/#slides"
    References: "references"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
